apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-mkaey-rd5h
spec:
  provider: azure
  secretObjects: # secretObjects defines the desired state of synced K8s secret objects
    - secretName: ingress-tls-csi
      type: kubernetes.io/tls
      data:
        - objectName: pythonapp-mkaey-de
          key: tls.key
        - objectName: pythonapp-mkaey-de
          key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "5048e5d8-f383-4e73-8eb8-48c879429acc"
    keyvaultName: "kv-mkaey-rd5h" # the name of the AKV instance
    objects: |
      array:
        - |
          objectName: pythonapp-mkaey-de
          objectType: secret
    tenantId: "619ecf84-fc66-443a-9e28-b1f131a14244"
